export enum Materials {
  CHIFFON = 'chiffon',
  COTTON = 'cotton',
  CREPE = 'crepe',
  DENIM = 'denim',
  LACE = 'lace',
  LEATHER = 'leather',
  LINEN = 'linen',
  SATIN = 'satin',
  SILK = 'silk',
  NYLON = 'nylon',
  POLYESTER = 'polyester',
  SPANDEX = 'spandex',
  VELVET = 'velvet',
  WOOL = 'wool',
  VISCOSE = 'viscose',
  TEXTILE = 'textile',
  SYNTHETIC = 'synthetic',
  RUBBER = 'rubber',
  FOAM = 'foam',
  PLASTIC = 'plastic',
}
